inc:
  # Blog Information
  title:        "TralahTek LLC"
  subtitle:     "Glimpse into the Future"
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Company information
  company:      TralahTek
  url:          https://tralahtek.com/
  facebook:     ""
  twitter:      tralahtek
  gplus:        '101183822199340201470'
  about_link:   https://tralahtek.com/about/

  # Product Information
  product_link: https://tralahtek.com/
  tagline:      "Get a modern blog for your company"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  tralahm

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true


 # Analytics
  analytics:
    google: true # Add tracking code in _includes/_google-analytics.html


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

plugins:
    - jekyll-assets
    - jekyll-paginate
include:
    - .htaccess
    - assets/*
exclude:
    - README*
timezone:    Africa/Nairobi

# Show future posts
future:      false
show_drafts: false
limit_posts: 0
# highlighter:    pygments


permalink:     /:categories/:year/:month/:day/:title/
paginate_path: 'page:num'
paginate: 10

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     ''
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: coderay

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  basename: /assets/
  dirname: assets
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
